# Search Configuration
search:
  max_results: 10
  fallback_order:
    - duckduckgo
    - tavily
    - google
  timeout: 30 # Default timeout for search requests
  retry:
    max_attempts: 3
    wait_exponential_multiplier: 1000 # milliseconds
    wait_exponential_max: 10000 # milliseconds

# URL Validation
url_validation:
  max_content_size: 10485760  # 10MB
  allow_video_urls: false
  allow_auth_required: false
  allowed_domains:
    - "*"
    - wikipedia.org
    - investopedia.com
    - cboe.com
    - cmegroup.com
    - td.com
    - fidelity.com.sg
    - ig.com
    - bankrate.com
    - stlouisfed.org
    - finance.yahoo.com
    - en.wikipedia.org
    - "*.com"
    - "*.org"
    - stackoverflow.com
    - github.com
    - arxiv.org
    - medium.com
  blocked_extensions: ['.exe', '.zip', '.rar']
  # Timeout for fetching URL content during validation/BM25 scoring
  url_fetch_request_timeout: 15 # seconds for individual request
  url_fetch_session_timeout_total: 60 # seconds for overall aiohttp session
  url_fetch_connection_timeout: 10 # seconds for connection phase

# Directories Configuration
directories:
  base: "Data" # Base directory for all output
  search:
    results: "SearchResults" # Subdirectory for search phase results
  scrape:
    base: "ScrapedResults"  # Subdirectory for scraping phase results
    pdfs: "pdfs"
    images: "images"
    html: "html"
    logs: "logs" # For individual scrape metadata JSONs
  logs: "logs" # For application system logs

# Web Scraping Configuration
scraping:
  max_concurrent: 5
  max_retries: 3
  retry_delay: 2 # seconds
  timeout: 30000 # milliseconds for playwright operations (30 seconds)
  headers:
    Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
    Accept-Language: "en-US,en;q=0.5"
    Accept-Encoding: "gzip, deflate, br"
  user_agents:
    - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
    - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
    - "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
  default_urls: # Example URLs if needed for testing
    - "https://example.com"
  modes: # Different scraping intensities
    basic:
      scrape_pdfs: false
      scrape_images: false
      scrape_math_symbols: false
    standard:
      scrape_pdfs: true
      scrape_images: true
      scrape_math_symbols: false
    complete:
      scrape_pdfs: true
      scrape_images: true
      scrape_math_symbols: true
  rate_limit:
    requests_per_minute: 60 # Not directly used by current sleep, but for reference
    delay_between_requests: 1 # seconds
  proxy:
    enabled: false
    type: "http"
    host: ""
    port: 8080
    username: ""
    password: ""

# BM25 Configuration
bm25:
  k1: 1.2
  b: 0.75

# Logging Configuration
logging:
  level: INFO
  file: "system.log" # Log file name, will be placed in directories.logs
  max_bytes: 10485760  # 10MB
  backup_count: 5
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  date_format: "%Y-%m-%d %H:%M:%S"
