# Search Configuration
search:
  max_results: 10
  fallback_order:
    - duckduckgo
    - tavily
    - google
  timeout: 30
  retry:
    max_attempts: 3
    wait_exponential_multiplier: 1000
    wait_exponential_max: 10000

# URL Validation
url_validation:
  max_content_size: 10485760  # 10MB
  allow_video_urls: false
  allow_auth_required: false
  allowed_domains:
    - "*"
    - wikipedia.org
    - investopedia.com
    - cboe.com
    - cmegroup.com
    - td.com
    - fidelity.com.sg
    - ig.com
    - bankrate.com
    - stlouisfed.org
    - finance.yahoo.com
    - en.wikipedia.org
    - "*.com"
    - "*.org"
    - stackoverflow.com
    - github.com
    - arxiv.org
    - medium.com

  # Results Storage
  results:
    directory: "Search_Results"
    file_prefix: "query_results_"
    timestamp_format: "%Y%m%d_%H%M%S"
    include_metadata: true

# Web Scraping Configuration
scraping:
  # Core Settings
  max_concurrent: 5
  max_retries: 3
  retry_delay: 2
  timeout: 30
  
  # Directories
  directories:
    base: "Data"
    scrape:
      base: "Scraped_Results"
      pdfs: "pdfs"
      images: "images"
      math: "math"
      html: "html"
  
  # Request Headers
  headers:
    Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
    Accept-Language: "en-US,en;q=0.5"
    Accept-Encoding: "gzip, deflate, br"
  
  # User Agents
  user_agents:
    - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
    - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
    - "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
    - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Safari/605.1.15"
  
  # Default URLs
  default_urls:
    - "https://huggingface.co/learn/agents-course/en/unit1/what-are-agents"
    - "https://cloud.google.com/discover/what-are-ai-agents"
  
  # Scraping Modes
  modes:
    basic:
      scrape_pdfs: false
      scrape_images: false
      scrape_math_symbols: false
    standard:
      scrape_pdfs: true
      scrape_images: true
      scrape_math_symbols: false
    complete:
      scrape_pdfs: true
      scrape_images: true
      scrape_math_symbols: true
  
  # Rate Limiting
  rate_limit:
    requests_per_minute: 60
    delay_between_requests: 1
  
  # Proxy Settings
  proxy:
    enabled: false
    type: "http"
    host: ""
    port: 8080
    username: ""
    password: ""

# URL Validation
url_validation:
  max_content_size: 10485760  # 10MB

# BM25 Configuration
bm25:
  k1: 1.2
  b: 0.75

# Logging
logging:
  level: INFO
  file: "logs/system.log"
  max_bytes: 10485760  # 10MB
  backup_count: 5
  
  # Directory
  directory: "logs"
  
  # Formatters
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  date_format: "%Y-%m-%d %H:%M:%S"
